#!/bin/bash
# Super APK downloader

exec() {
  apk_var=$1
 
  casperjs apk_installer.js --apk=$apk_var

  if [ $? -eq 0 ]
  then
    echo "Find apk path, copy the apk file and uninstall it"
    node copy_uninstall.js $apk_var
  else
    echo "Could not install: $apk_var" >&2
  fi

}

if [ "$1" != "" ]; then
    echo "APK: $1"
    exec $1
else
    echo "no apk prameter"
fi
